//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaMGR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JakTraficEntities : DbContext
    {
        public JakTraficEntities()
            : base("name=JakTraficEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategorie> Kategorie { get; set; }
        public virtual DbSet<Linie> Linie { get; set; }
        public virtual DbSet<LinieRaport> LinieRaport { get; set; }
        public virtual DbSet<Oceny> Oceny { get; set; }
        public virtual DbSet<Odjazdy> Odjazdy { get; set; }
        public virtual DbSet<Odpowiedzi> Odpowiedzi { get; set; }
        public virtual DbSet<Posty> Posty { get; set; }
        public virtual DbSet<Przystanki> Przystanki { get; set; }
        public virtual DbSet<PrzystankiRaport> PrzystankiRaport { get; set; }
        public virtual DbSet<Trasy> Trasy { get; set; }
        public virtual DbSet<TrasyRaport> TrasyRaport { get; set; }
        public virtual DbSet<DniSwiateczne> DniSwiateczne { get; set; }
    }
}
