//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaMGR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oceny
    {
        public int Id { get; set; }
        public int Punktualnosc { get; set; }
        public int Czystosc { get; set; }
        public int Kultura_os_kierowcy { get; set; }
        public int Komfort_jazdy { get; set; }
        public int Poczucie_bezpieczenstwa { get; set; }
        public double Suma { get; set; }
        public string Symbol_linii { get; set; }
        public string Uzytkownik { get; set; }
    }
}
