//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaMGR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odjazdy
    {
        public int Id { get; set; }
        public int Nr_przystanku { get; set; }
        public string Typ { get; set; }
        public string Symbol_linii { get; set; }
        public string Nazwa_trasy { get; set; }
        public string Godziny { get; set; }
    
        public virtual Przystanki Przystanki { get; set; }
    }
}
