//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaMGR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odpowiedzi
    {
        public int Id { get; set; }
        public string Tresc { get; set; }
        public string Uzytkownik { get; set; }
        public int Id_Post { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Posty Posty { get; set; }
    }
}
