//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaMGR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przystanki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Przystanki()
        {
            this.Odjazdy = new HashSet<Odjazdy>();
            this.PrzystankiRaport = new HashSet<PrzystankiRaport>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public int Numer { get; set; }
        public string Strefa { get; set; }
        public string Nazwa_rozklad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odjazdy> Odjazdy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrzystankiRaport> PrzystankiRaport { get; set; }
    }
}
